variable "rgs" {}
variable "vnets" {}
variable "snets" {}
variable "nics" {}
variable "pips" {}
variable "sas" {}
variable "scs" {}
variable "vms" {}
variable "nsgs" {}
variable "associations" {}
variable "bhs" {}
variable "kvs" {}
variable "lbs" {}